### ISSUE TITLE
GH Actions Pipeline Is Broken

### ISSUE THREAD

**Issue by Xtigyro** [puppetlabs/puppetserver-helm-chart#119]
## Describe the Bug
- https://github.com/puppetlabs/puppetserver-helm-chart/runs/6882727644?check_suite_focus=true#step:7:10

CC: @davidphay @underscorgan

**Comment by davidphay** [comment]
![image](https://user-images.githubusercontent.com/17404140/174006222-28385ced-100a-49ae-965f-d47fcefe1984.png)

I think the problem is because `grep` return 2 values ?

I'm not 100% sure, but if we only want the helm chart version we should filter with something like this `grep '^version:' Chart.yaml | awk '{print $2}'`, what are you thinking?

**Comment by Xtigyro** [comment]
@davidphay Yeah - that's exactly what changed - we moved the dependencies in the same file. 🥇

**Comment by davidphay** [comment]
Ahah correct, I had already forgotten... 
I don't have access, so i'll let you update it !

**Comment by Xtigyro** [comment]
@davidphay Yup, thanks!
FYI: I'm still working on your access. We'll get there!
