### ISSUE TITLE
Does the Helm Chart support puppetserver 8?

### ISSUE THREAD

**Issue by cpiment** [puppetlabs/puppetserver-helm-chart#210]
## Use Case
I would like to deploy Puppet Server 8 using this Helm chart. Is this possible? It seems that the puppet server image version is set to 7.13 by default.

## Describe the Solution You Would Like
A parameter or set of parameters in the Helm chart that would allow to switch Puppet Server versions

## Describe Alternatives You've Considered
Modify the chart manually

**Comment by Xtigyro** [comment]
@cpiment Have you tried setting the value for [that line](https://github.com/puppetlabs/puppetserver-helm-chart/blob/master/values.yaml#L66)?

**Comment by cpiment** [comment]
HI @Xtigyro , I thought there would be some other dependent components that should be upgraded to other versions too. I will try that change and get back here with my findings. Thanks!

**Comment by Xtigyro** [comment]
@cpiment Most probably you'd need to set a higher value for PuppetDB too. Let me know what happens. Also - please feel free to send our way a PR. The whole chart is completely community supported.

**Comment by cpiment** [comment]
Hi @Xtigyro I've been able to start Puppet Server and puppet DB using this `values.yaml`:
```yaml
puppetserver:
  tag: 8.4.0-latest
puppetdb:
  tag: 8.3.0-latest
```
And everything started fine. The problem is that I have tried to run Puppet Agent latest version in a Windows host and I have not been able to start it (not a problem with Puppet Server, but with the agent itself), so I have rolled it back to Puppet Server 7.

**Comment by anthonysomerset** [comment]
So i can confirm upgrade from 7 to puppetserver 8 works just fine when updating your values to add the puppet 8 images - with custom/imported CA and multi- CA and multi-compiler just fine

it "might" be beneficial to introduce a new config item that defaults to puppet version 7  which presets the values of those tags for 7 or 8 (or later 9) based on the config value because it would at least avoid scenarios where if a user is careless they might try to run a V8 only compatible puppetdb but only v7 server or the other way around

**Comment by davidphay** [comment]
Thanks for the feedback! 
Please feel free to send our way a PR if you have the time and energy for helping us.

For now I close this issue since you confirm the compatibility.
